### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by FewerElk** [bymatej/minecraft-server#5]
Hi, I don't know where put this.
This server clone à Minecraft server from spigot paper sponger or mojang or it is a server created from a to z by you ?
If you created the entire server, I ´ve a few questions for you about requests and protocol used by Minecraft.
This question will be for my project https://github.com/PythonInMinecraft/Minecraft-server

**Comment by bymatej** [comment]
> Hi, I don't know where put this.
> This server clone à Minecraft server from spigot paper sponger or mojang or it is a server created from a to z by you ?
> If you created the entire server, I ´ve a few questions for you about requests and protocol used by Minecraft.
> This question will be for my project https://github.com/PythonInMinecraft/Minecraft-server

Hi! 

No, it's nothing I created from a-z. It's an old project of mine I used to spin up a server to play with my friends online. :) 

This project was just a docker image that has a script which, on start, selects the server - Vanilla server, Spigot, Paper, or Forge. 
This is defined by `MINECRAFT_FLAVOR` variable.

So this is nothing special. I just used the existing server(s), and this is a wrapper that helps me start them easily. :) 
Cheers!


--
Regards, 
Matej J.
